name: dice_roller
description: A minimal Flutter dice rolling app
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
